# Data Preprocessing - Chronic Kidney Disease

In [1]:
import pandas as pd 
dataset = pd.read_csv("kidney_disease.csv")
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [2]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

## finding missing values

In [3]:
# find missing values - mv
mv_details = dataset.isnull().sum()
mv_details

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [4]:
# quan qual 
from Univariate_analysis import Univariate
Univariate = Univariate(dataset)
quan , qual = Univariate.quanQual()
quan=quan[1:]
print("quan :",quan , "\nqual :", qual)

quan : ['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']
qual : ['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

## replacing missing values

In [5]:
dataset[quan]

      age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0    48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    NaN  NaN  15.4
1     7.0  50.0  1.020  4.0  0.0    NaN  18.0  0.8    NaN  NaN  11.3
2    62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    NaN  NaN   9.6
3    48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4    51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    NaN  NaN  11.6
..    ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 11 columns]

In [6]:
####  replace quan missing values with simple Imputer 

import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 
imp = SimpleImputer(missing_values = np.nan, strategy='median')
imp.fit(dataset[quan])
quan_dataset = imp.transform(dataset[quan])
quan_dataset=pd.DataFrame(quan_dataset, columns=quan)
quan_dataset

      age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0    48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2  138.0  4.4  15.4
1     7.0  50.0  1.020  4.0  0.0  121.0  18.0  0.8  138.0  4.4  11.3
2    62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8  138.0  4.4   9.6
3    48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4    51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4  138.0  4.4  11.6
..    ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 11 columns]

In [7]:
# replace qual missing values with most repeated data
# approach - 1 
# for column in mv_col_qual:
#     dataset.fillna({column:dataset[column].mode()[0]},inplace=True)
# dataset

# replace qual missing values with 'unknown' - constant string
# approach - 2
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 
imp = SimpleImputer(missing_values = np.nan, strategy='constant', fill_value='unknown')
imp.fit(dataset[qual])
qual_dataset = imp.transform(dataset[qual])
qual_dataset=pd.DataFrame(qual_dataset,columns=qual)
qual_dataset

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,unknown,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,unknown,normal,notpresent,notpresent,38,6000,unknown,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,unknown,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

##  concat both dataframe

In [8]:
preprocessed_dataset = pd.concat([quan_dataset,qual_dataset], axis=1)    # concat axis - 1 (column)
preprocessed_dataset

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,...,38,6000,unknown,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,...,31,7500,unknown,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [9]:
preprocessed_dataset.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [10]:
# preprocessed_dataset['classification'].replace({'ckd':1,'notckd':0},inplace=True)

In [11]:
preprocessed_dataset['classification'] = preprocessed_dataset['classification'].str.strip()
preprocessed_dataset['pcv'] = preprocessed_dataset['pcv'].str.strip()
preprocessed_dataset['wc'] = preprocessed_dataset['wc'].str.strip()
preprocessed_dataset['dm'] = preprocessed_dataset['dm'].str.strip()
preprocessed_dataset['cad'] = preprocessed_dataset['cad'].str.strip()

In [12]:
preprocessed_dataset['wc'] = preprocessed_dataset['wc'].replace(['?','unknown'],'0')
preprocessed_dataset['wc'].unique()

array(['7800', '6000', '7500', '6700', '7300', '0', '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '7100', '11800', '9400', '5500', '5800', '13200',
       '12500', '5600', '7000', '11900', '10400', '10700', '12700',
       '6800', '6500', '13600', '10200', '9000', '14900', '8200', '15200',
       '5000', '16300', '12400', '10500', '4200', '4700', '10900', '8100',
       '9500', '2200', '12800', '11200', '19100', '12300', '16700',
       '2600', '26400', '8800', '7400', '4900', '8000', '12000', '15700',
       '4100', '5700', '11500', '5400', '10800', '9900', '5200', '5900',
       '9300', '9700', '5100', '6600'], dtype=object)

In [13]:
preprocessed_dataset['pcv'] = preprocessed_dataset['pcv'].replace(['?','unknown'],'0')

In [14]:
preprocessed_dataset['pcv'].unique()

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', '0',
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '52', '14',
       '22', '18', '42', '17', '46', '23', '19', '25', '41', '26', '15',
       '21', '43', '20', '47', '9', '49', '50', '53', '51', '54'],
      dtype=object)

In [15]:
preprocessed_dataset['rc'] = preprocessed_dataset['rc'].replace(['\t?','unknown'],'0')

In [16]:
preprocessed_dataset['rc'].unique()

array(['5.2', '0', '3.9', '4.6', '4.4', '5', '4.0', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6.0', '5.0', '2.1', '5.6', '2.3',
       '2.9', '2.7', '8.0', '3.3', '3.0', '3', '2.4', '4.8', '5.4', '6.1',
       '6.2', '6.3', '5.1', '5.8', '5.5', '5.3', '6.4', '5.7', '5.9',
       '6.5'], dtype=object)

In [17]:
preprocessed_dataset['rc']=preprocessed_dataset['rc'].astype('float64')
preprocessed_dataset['pcv']=preprocessed_dataset['pcv'].astype('int64')
preprocessed_dataset['wc']=preprocessed_dataset['wc'].astype('int64')

In [18]:
preprocessed_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             400 non-null    float64
 1   bp              400 non-null    float64
 2   sg              400 non-null    float64
 3   al              400 non-null    float64
 4   su              400 non-null    float64
 5   bgr             400 non-null    float64
 6   bu              400 non-null    float64
 7   sc              400 non-null    float64
 8   sod             400 non-null    float64
 9   pot             400 non-null    float64
 10  hemo            400 non-null    float64
 11  rbc             400 non-null    object
 12  pc              400 non-null    object
 13  pcc             400 non-null    object
 14  ba              400 non-null    object
 15  pcv             400 non-null    int64
 16  wc              400 non-null    int64
 17  rc              400 non-null    float64
 18  htn             400 non-null    object
 19  dm              400 non-null    object
 20  cad             400 non-null    object
 21  appet           400 non-null    object
 22  pe              400 non-null    object
 23  ane             400 non-null    object
 24  classification  400 non-null    object
dtypes: float64(12), int64(2), object(11)
memory usage: 78.3+ KB

In [19]:
preprocessed_dataset.columns.to_list()

['age',
 'bp',
 'sg',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hemo',
 'rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [23]:
pd.get_dummies(preprocessed_dataset,drop_first=True,dtype=int)
preprocessed_dataset.head()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,4.4,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,4.4,...,38,6000,0.0,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,4.4,...,31,7500,0.0,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,4.4,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [21]:
"""
To handle missing values in the CKD dataset, I used the SimpleImputer from scikit-learn. For numerical features, 
I chose the median strategy since medical data is often skewed and median is more robust to outliers. 
For categorical features, I used the constant strategy and filled missing values with "Unknown" to preserve potential information 
in the missingness pattern.

"""

'\nTo handle missing values in the CKD dataset, I used the SimpleImputer from scikit-learn. For numerical features, \nI chose the median strategy since medical data is often skewed and median is more robust to outliers. \nFor categorical features, I used the constant strategy and filled missing values with "Unknown" to preserve potential information \nin the missingness pattern.\n\n'

In [22]:
# save the preprocessed file 
preprocessed_dataset.to_csv("preprocessed_CKD.csv", index=False)