In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("kidney_disease.csv")

In [3]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [5]:
#1)Replace the missing value with central tendency-Mean Median Mode
#2)Entire Row delete
#3)REspective to the problem ,have to replace the missing values
#4)Consider this as a semi supervised, create a model, so that we can predict the missing values.

In [6]:
dataset.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [7]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [8]:
dataset.dropna(inplace=True)

In [9]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [10]:
dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [11]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [23]:
quan,qual=quanQual(dataset)

In [13]:
dataset[quan]

      id   age    bp     sg   al   su    bgr     bu   sc    sod  pot  hemo
3      3  48.0  70.0  1.005  4.0  0.0  117.0   56.0  3.8  111.0  2.5  11.2
9      9  53.0  90.0  1.020  2.0  0.0   70.0  107.0  7.2  114.0  3.7   9.5
11    11  63.0  70.0  1.010  3.0  0.0  380.0   60.0  2.7  131.0  4.2  10.8
14    14  68.0  80.0  1.010  3.0  2.0  157.0   90.0  4.1  130.0  6.4   5.6
20    20  61.0  80.0  1.015  2.0  0.0  173.0  148.0  3.9  135.0  5.2   7.7
..   ...   ...   ...    ...  ...  ...    ...    ...  ...    ...  ...   ...
395  395  55.0  80.0  1.020  0.0  0.0  140.0   49.0  0.5  150.0  4.9  15.7
396  396  42.0  70.0  1.025  0.0  0.0   75.0   31.0  1.2  141.0  3.5  16.5
397  397  12.0  80.0  1.020  0.0  0.0  100.0   26.0  0.6  137.0  4.4  15.8
398  398  17.0  60.0  1.025  0.0  0.0  114.0   50.0  1.0  135.0  4.9  14.2
399  399  58.0  80.0  1.025  0.0  0.0  131.0   18.0  1.1  141.0  3.5  15.8

[158 rows x 12 columns]

In [14]:
import numpy as np
from sklearn.impute import SimpleImputer

# Define the imputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer on the numerical columns (quan) of the dataset
imp.fit(dataset[quan])

# Transform the dataset by replacing missing values with the mean
df = imp.transform(dataset[quan])

# Convert the resulting array back into a DataFrame with the same column names
df = pd.DataFrame(df, columns=quan)

In [15]:
df

        id   age    bp     sg   al   su    bgr     bu   sc    sod  pot  hemo
0      3.0  48.0  70.0  1.005  4.0  0.0  117.0   56.0  3.8  111.0  2.5  11.2
1      9.0  53.0  90.0  1.020  2.0  0.0   70.0  107.0  7.2  114.0  3.7   9.5
2     11.0  63.0  70.0  1.010  3.0  0.0  380.0   60.0  2.7  131.0  4.2  10.8
3     14.0  68.0  80.0  1.010  3.0  2.0  157.0   90.0  4.1  130.0  6.4   5.6
4     20.0  61.0  80.0  1.015  2.0  0.0  173.0  148.0  3.9  135.0  5.2   7.7
..     ...   ...   ...    ...  ...  ...    ...    ...  ...    ...  ...   ...
153  395.0  55.0  80.0  1.020  0.0  0.0  140.0   49.0  0.5  150.0  4.9  15.7
154  396.0  42.0  70.0  1.025  0.0  0.0   75.0   31.0  1.2  141.0  3.5  16.5
155  397.0  12.0  80.0  1.020  0.0  0.0  100.0   26.0  0.6  137.0  4.4  15.8
156  398.0  17.0  60.0  1.025  0.0  0.0  114.0   50.0  1.0  135.0  4.9  14.2
157  399.0  58.0  80.0  1.025  0.0  0.0  131.0   18.0  1.1  141.0  3.5  15.8

[158 rows x 12 columns]

In [24]:
cate=dataset[qual]

In [25]:
cate

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,abnormal,abnormal,present,notpresent,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,abnormal,abnormal,present,notpresent,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,normal,abnormal,present,present,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,abnormal,abnormal,notpresent,notpresent,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [26]:
two=[df,cate]

In [27]:
preprocessed=pd.concat(two,axis=1)

In [28]:
preprocessed

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9.0,53.0,90.0,1.020,2.0,0.0,70.0,107.0,7.2,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11.0,63.0,70.0,1.010,3.0,0.0,380.0,60.0,2.7,131.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14.0,68.0,80.0,1.010,3.0,2.0,157.0,90.0,4.1,130.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,20.0,61.0,80.0,1.015,2.0,0.0,173.0,148.0,3.9,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [29]:
preprocessed.isnull().sum()

id                133
age               133
bp                133
sg                133
al                133
su                133
bgr               133
bu                133
sc                133
sod               133
pot               133
hemo              133
rbc               133
pc                133
pcc               133
ba                133
pcv               133
wc                133
rc                133
htn               133
dm                133
cad               133
appet             133
pe                133
ane               133
classification    133
dtype: int64

In [21]:
preprocessed.to_csv("PreprocessedCKDdata.csv",index=False)